### PR TITLE
adding a path option

### LINKED ISSUE #72: generator should support --path option
It is common to create apps in react-redux using the [fractal project structure](https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure) outlined in the manual. Currently a generator can be used to easily create a component in the main project folder, but you can't use it to create a component inside of a route. Using [ember-cli](http://ember-cli.com/user-guide/#using-pods) you can use the `--path <path>` option with some generators to create the files in a subfolder.

In redux-cli it might look like this:

``` bash
redux g dumb butter --path routes/about
# creates a component in src/routes/about/components/Butter/
# creates a spec file in tests/routes/about/components/Butter/
```

One of the best reasons to use a generator is that it automatically creates the test files for you. Having to manually create the test files when creating a component within a route is an example of why people often prefer to use a generator.

The proposal here is that if someone wants to prefix the thing they generate with a path that should be easy to do. I personally think it should apply to any blueprint.

_Note:_ I might build this feature soon.

### PR DESCRIPTION
**Pull request by heygrady**
fixes #72

### CODE REVIEW

**Comment by baohx2000** [comment]
@heygrady, looks like this needs a rebase.  It would be awesome to get this merged!

**Comment by ericwooley** [comment]
@SpencerCDixon This has been an open PR for quite a while, any chance of getting this in? It would be really useful.

**Comment by prescottprue** [comment]
+1 Getting this is would be awesome.

**Comment by simoneduca** [comment]
👍

**Comment by anithri** [comment]
There is no problem with merging this functionality.  But it needs tests first.

@heygrady do you want to add those, or should we open that to contributors?

**Comment by prescottprue** [comment]
@heygrady Is there a reason this was closed without merging? Was pretty excited for this feature.

**Comment by heygrady** [comment]
This more than a year old. I've lost interest. There's nothing special about the code I added. Someone can take over.

**Pull request closed without merging**
