### PR TITLE
#10 cli default

### PR DESCRIPTION
**Pull request by jamesr73**
Addresses #10

Adds checks for required arguments and outputs help if they are missing. Reports on unknown commands.

Syncs up command descriptions between top-level and sub-command level usage.

### CODE REVIEW

**Comment by anithri** [comment]
The functionality looks good.  It will needs tests before it gets accepted though.

@jamesr73 Do you want to write the tests, or should we ask for contributors?

**Comment by jamesr73** [comment]
Wow, been a while since I looked at this, and now I have conflicts :smirk:

Testing these changes will need tests for the CLI in the first instance. And they may well require an additional change for [Commander #297](https://github.com/tj/commander.js/issues/297).

Let me take a look and get back to you.

It's probably also worth upgrading the commander dependency, newest should support sub command aliases directly. Thoughts?

**Comment by jamesr73** [comment]
Resolved my conflicts. I can write tests but I'm thinking it's worth waiting until #99 is merged.

**Comment by anithri** [comment]
Is there any need for this given #110?

**Comment by jamesr73** [comment]
No, #110 supersedes this.

**Pull request closed without merging**
