### PR TITLE
setup project to use Prettier as code formatter and eslint rules set

### PR DESCRIPTION
**Pull request by anithri**
[prettier code formatter](https://github.com/prettier/prettier)

Reformats code to meet standards, easy to run, easier to keep linter happy.

I'm not convinced we need this, but I thought I'd try it to see how much work it would take to migrate, which was not much.

From what I saw, most of the formatting changes were whitespacing and wrapping, along with a bunch of quote changes.

What do you think?

### CODE REVIEW

**Comment by anithri** [comment]
BTW, this PR will need to be redone if any PR's are accepted to master before this one, otherwise the merge will be hell.

**Comment by anithri** [comment]
What do you think about a task that generates each of the blueprints, and we lint the results of the generation.

**Comment by anithri** [comment]
This is the only descepency that lint find *after* pretty runs.
```
/home/scottp/4winds/redux-cli/blueprints/duck/files/__root__/__duck__/__test__.js
  14:1  error  Expected indentation of 2 spaces but found 4  indent
  15:1  error  Expected indentation of 4 spaces but found 6  indent

✖ 2 problems (2 errors, 0 warnings)
  2 errors, 0 warnings potentially fixable with the `--fix` option.
```
so it wants
```
export default function(state = defaultState, action) {
  switch (action.type) {
    default:
      return state;
  }
}
```
to be
```
export default function(state = defaultState, action) {
  switch (action.type) {
  default:
    return state;
  }
}
```
And so I've been editing it back after i `yarn run pretty`

**Comment by anithri** [comment]
I 'm not going to even try to do standard.js unless i get some buy in for no semi-colons.

I come from ruby and my biggest gripe with javascript is all the damn punctuation.
But I can live with them on or off.

**Comment by jamesr73** [comment]
> What do you think?

👍  I can re-enable prettier format on save in my editor 😉 

> eslint errors in switch

/*eslint indent: ["error", 2, { "SwitchCase": 1 }]*/

**Comment by jamesr73** [comment]
> What do you think about a task that generates each of the blueprints, and we lint the results of the generation.

If blueprints have options and logic they should be explicitly tested. And the tests could include linting the output. That should ensure all the permutations of output are covered.

**Pull request merged**
