### PR TITLE
Add Models - RcCollectionRaw and RcCollection

### PR DESCRIPTION
**Pull request by anithri**
This class creates an ordered list of rc files that will be read.
It uses the BLUEPRINT_CONFIG env variable to add files to the default
search paths.

WIP

### CODE REVIEW

**Comment by anithri** [comment]
RcCollectionRaw is a model that to get a list of paths with blueprintrc files that exist.

It processes files from:
1. CLI arguments (maybe?  needs wired to cli), parses it as a colon separated list of paths
2. if BLUEPRINT_CONFIG exists, parses it as a colon separated list of paths
3. Project files in the cwd and working up the filesystem until it finds a .blueprintrc file
4. User files in home directory and other common config dirs for linux, osx, and windows
5. System files in common config dirs for linux, osx, and windows. (Windows and OSX need review and testing)

The paths are tested to be sure that they exist and are files

**Comment by anithri** [comment]
```
collection = new RcCollection(files: ['/path/to/a','/path/to/b']);
collection.collection // {'/path/to/a': aData, '/path/to/b': bData}
data = collection.data(defaults);
data // data merged defaults, bData, aData
data.assembly.configFiles // ['/path/to/a','/path/to/b'])
```

**Comment by anithri** [comment]
blueprintrc files may have 
```
{
// single line comments
/* multi 
    line 
    column */
  "Data": /* inlineComment */ "Value",
  "other": "Data", /* another Inline */
  "again": "Data" /* another Inline */ ,
}

```

**Comment by jamesr73** [comment]
Looks good.

The CLI is currently configured to look for `BLUEPRINT_` environment variables to set command line arguments. So if we add a `--config` CLI option it would be set by `BLUEPRINT_CONFIG` and overridden by `--config`. Looks messy to handle `BLUEPRINT_CONFIG` both in the CLI and the RC mechanism, should we just pass in the value from the CLI?

Suspect we need platform specific path separators rather than just using colon:

`C:\path\to\.blueprintrc:C:\other\path\to\.blueprintrc`

**Comment by anithri** [comment]
I'll leave it to the cli to deal with the ENV then.  Is that true for other options passed via ENV as well?  I'd be happy to just accept an obj containing the parsed structure and values, is that possible?  I'll remove my code that deals with that.  I've been assuming that the CLI had top priority, and that ENV had 2nd.

<expresses derogatory thoughts about windows>.  Ahem, do we need a different path separator?  It's not something the shell would use, so does it matter to us? Not sure.

**Comment by anithri** [comment]
Refactored into #132.  Closing this earlier draft unmerged.

**Pull request closed without merging**
