### PR TITLE
ProjectSettings loads default settings

### PR DESCRIPTION
**Pull request by anithri**
We're going to need a default set of settings so the bp can have the minimum settings needed to run.

Put here for discussion, but after #127, I this functionality actually belongs in `src/cli/environment`.

### CODE REVIEW

**Comment by jamesr73** [comment]
The default settings should be just enough to support `bp init` (or `bp new`)?

**Comment by anithri** [comment]
Hi I'm scott.  And I over-engineer.  Especially when I'm TDDing.  And I may have taken the dependency injection (DI) a bit over board.  But the chain works pretty well, and has no noticeable effect on performance.  I'm integrating it with the Blueprint collection next.  

They key change to the "API" is that the Project Settings class is a Facade that has 4 child objects.
1. **RcCollection**.  This is the worker class that finds, reads and aggregates the rcFiles.  By the time the commands start executing, this class has done it's job.  I'm including it for introspection and the config command.
2. **RcData**.  This is the aggragated data structure, ready for use.
3. **BlueprintCollection** This is used to organize, find, and instantiate blueprints.
4. **Api** Used to interact with the user.

**Comment by anithri** [comment]
### RcCollection
Primary Interface.
* `rcc.data(defaults={})` returns the aggragated set of data, optionally merged with another set of defaults.
* `rcc.rcFiles` Returns an array of the rc files actually used.  
* `rcc.collection` Returns an object with key value pairs of the filename with the data loaded from that file.

**Comment by anithri** [comment]
### RcData
Primary Interface
* `rc.for('deep.key.path[0]')` returns the value at the described key in `rc.data`.
* `rc.forBp(bpName, 'deep.path')` returns the value for `bp.bpName (combined with common) at the key
* `rc.with({defaults = {},  common = this.atCommon(), data = this.data, priority = {})` returns a new RcData object created from the args 
* `rc.withBp(bpName,defaults = {},  common = this.atCommon(), priority = {})` returns a new RcData object created from defaults, common bp, named, blueprint, and priority

I'm unsure if we should be spawning rc objects for the two Bp functions, but it sure is convienent, as it still allows `rc.for(...)` to be used for the subset and makes an easy way to apply the common settings.

**Comment by jamesr73** [comment]
Hi Scott the over-engineer. Looks very interesting. I'm visiting family for a few days, looking forward to reviewing this on the weekend..

**Comment by jamesr73** [comment]
`rc` / `rcc` comments really belong on #131 ?

**Pull request closed without merging**
